# Generated by Django 4.0.6 on 2022-12-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.IntegerField(blank=10, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.priority'),
        ),
    ]
